// <auto-generated />
namespace CLMLTEMA.MODELS.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class Add_LineGroupName_Field_To_RouteLines_Entity : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Add_LineGroupName_Field_To_RouteLines_Entity));
        
        string IMigrationMetadata.Id
        {
            get { return "202506191904468_Add_LineGroupName_Field_To_RouteLines_Entity"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
