using System;
using CL.STRUCTURES.CLASSES.PresentationEntities;
using CL.STRUCTURES.INTERFACES;

namespace CLMLTEMA.MODELS
{
    /// <summary>
    /// Represents a calendar appointment linked to external services like Outlook or Gmail.
    /// </summary>
    public class CalendarAppointment : BaseEntity, IClDatabaseServices
    {
        /// <summary>
        /// Appointment ID generated by Outlook or Gmail calendar services.
        /// </summary>
        public string AppointmentId { get; set; }

        /// <summary>
        /// Domain identifier (e.g., email provider).
        /// </summary>
        public int Domain { get; set; }

        /// <summary>
        /// Status of the appointment.
        /// </summary>
        public int Status { get; set; }

        /// <summary>
        /// Associated route line ID.
        /// </summary>
        public int RouteLineId { get; set; }

        /// <summary>
        /// Associated route assignment ID.
        /// </summary>
        public int RouteAssignmentId { get; set; }

        /// <summary>
        /// Route assignment details.
        /// </summary>
        public RouteAssignment RouteAssignment { get; set; }

        /// <summary>
        /// Route line details.
        /// </summary>
        public RouteLine RouteLine { get; set; }
    }

    /// <summary>
    /// Stores credentials and configuration for a user's email calendar access.
    /// </summary>
    public class UserCalendarCredentials
    {
        /// <summary>
        /// User email address.
        /// </summary>
        public string Email { get; set; }

        /// <summary>
        /// Password for the email account.
        /// </summary>
        public string EmailPassword { get; set; }

        /// <summary>
        /// Email type (e.g., Outlook or Gmail).
        /// </summary>
        public int EmailType { get; set; }
    }

    /// <summary>
    /// Settings for scheduling and integration with calendar services.
    /// </summary>
    public class SchedulingSetting
    {
        /// <summary>
        /// Company ID.
        /// </summary>
        public int CompanyId { get; set; }

        /// <summary>
        /// Indicates whether scheduling is enabled.
        /// </summary>
        public bool UseScheduling { get; set; }

        /// <summary>
        /// Gmail service account email.
        /// </summary>
        public string GmailServiceAccount { get; set; }

        /// <summary>
        /// Password for the Gmail service account.
        /// </summary>
        public string GmailServiceAccountPassword { get; set; }

        /// <summary>
        /// Outlook service URL.
        /// </summary>
        public string OutlookServiceURL { get; set; }
    }
    
    public class RouteInfoForAppointment
    {
        /// <summary>
        /// Route or appointment name.
        /// </summary>
        public string Name { get; set; }

        /// <summary>
        /// Weeks the route is active.
        /// </summary>
        public string Weeks { get; set; }

        /// <summary>
        /// Days the route is active.
        /// </summary>
        public string Days { get; set; }

        /// <summary>
        /// Appointment address.
        /// </summary>
        public string Address { get; set; }

        /// <summary>
        /// Card name associated with the route.
        /// </summary>
        public string CardName { get; set; }

        /// <summary>
        /// Expiration date for the route or appointment.
        /// </summary>
        public DateTime ExpirationDate { get; set; }

        /// <summary>
        /// Route type.
        /// </summary>
        public int Type { get; set; }

        /// <summary>
        /// Geographic latitude.
        /// </summary>
        public double Latitude { get; set; }

        /// <summary>
        /// Geographic longitude.
        /// </summary>
        public double Longitude { get; set; }

        /// <summary>
        /// Route line ID.
        /// </summary>
        public int RouteLineId { get; set; }

        /// <summary>
        /// Route frequency ID.
        /// </summary>
        public int RouteFrequencyId { get; set; }

        /// <summary>
        /// Scheduled visiting start time.
        /// </summary>
        public string VisitingTime { get; set; }

        /// <summary>
        /// Scheduled visiting end time.
        /// </summary>
        public string VisitEndTime { get; set; }
    }

    /// <summary>
    /// Supported user email domains.
    /// </summary>
    public enum UserEmailDomain
    {
        /// <summary>
        /// Outlook domain.
        /// </summary>
        Outlook = 1,

        /// <summary>
        /// Gmail domain.
        /// </summary>
        Gmail = 2
    }

    /// <summary>
    /// Days of the week for Gmail calendar integration.
    /// </summary>
    public enum GmailCalendarDaysOfWeek
    {
        /// <summary>
        /// Sunday
        /// </summary>
        SU = 0,

        /// <summary>
        /// Monday
        /// </summary>
        MO = 1,

        /// <summary>
        /// Tuesday
        /// </summary>
        TU = 2,

        /// <summary>
        /// Wednesday
        /// </summary>
        WE = 3,

        /// <summary>
        /// Thursday
        /// </summary>
        TH = 4,

        /// <summary>
        /// Friday
        /// </summary>
        FR = 5,

        /// <summary>
        /// Saturday
        /// </summary>
        SA = 6
    }
}