using System;
using System.Collections;
using CL.STRUCTURES.CLASSES.PresentationEntities;
using CL.STRUCTURES.INTERFACES;

namespace CLMLTEMA.MODELS
{
    /// <summary>
    /// Represent the model of the document that was created offline and should will send to SAP
    /// </summary>
    public class SyncDocument : BaseEntity, IClDatabaseServices
    {
        /// <summary>
        /// Id of the user assignation that create the document
        /// </summary>
        public int UserAssignId { get; set; }
        /// <summary>
        /// Date when the document is was created in the mobile
        /// </summary>
        public DateTime OfflineDate { get; set; }
        /// <summary>
        /// Number of attempts to send to SAP
        /// </summary>
        public int BackupsRequestAmount { get; set; }
        /// <summary>
        /// Type of the transaction (Order, Quotation, CreditInvoice...)
        /// </summary>
        public string TransactionType { get; set; }
        /// <summary>
        /// Status of the transaction
        /// </summary>
        public string TransactionStatus { get; set; }
        /// <summary>
        /// Details of the transaction process
        /// </summary>
        public string TransactionDetail { get; set; }
        /// <summary>
        /// DocEntry of the created document in SAP
        /// </summary>
        public int DocEntry { get; set; }
        /// <summary>
        /// DocNum of the created document in SAP
        /// </summary>
        public int DocNum { get; set; }
        /// <summary>
        /// Document key generated by application
        /// </summary>
        public string DocumentKey { get; set; }
        /// <summary>
        /// Type of the document to create
        /// </summary>
        public string DocumentType { get; set; }
        /// <summary>
        /// Serialized document to create
        /// </summary>
        public string RawDocument { get; set; }
        /// <summary>
        /// Navigation property to make a relationship between users assigns and synchronized documents
        /// </summary>
        public UserAssign UserAssign { get; set; }
    }
    
    public class SyncDocumentsPaged
    {
        public IEnumerable SyncDocuments { get; set; }
        public int Count { get; set; }
    }
    
    public class SyncDocumentFilter
    {
        public string Filter { get; set; }
        public string Status { get; set; }
        public string Type { get; set; }
        public DateTime From { get; set; }
        public DateTime To { get; set; }
        public int Skip { get; set; }
        public int Take { get; set; }
    }

    public class SyncDocumentStatus
    {
        public int Count { get; set; }
        public int Errors { get; set; }
        public string Status { get; set; }
    }
}